config/routes.rb
Yakicame1::Application.routes.draw do

  
  get "users/show",path: "users/show/:name"
  
  resources :tweets,except: [:new, :show] do
  resource :favorite, only: [:create, :destroy]
  end  
  
  resources :users,only: [:index] do
    resource :follow, only: [:create,:destroy]
  end  
  get "homes/index"

  devise_for :users 

  unauthenticated do
    as :user do
      root to: 'homes#index'
    end
  end  
  root to: 'tweets#index'

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  attr_accessible :tweet
  belongs_to :user
  belongs_to :tweet
  validates :tweet_id, uniqueness: {scope: :user_id}
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  attr_accessible :followed_user
  default_scope includes(:user,:followed_user)
  belongs_to :user
  belongs_to :followed_user,class_name: User,foreign_key: :followed_id
  validate :not_follow_oneself
  validates :followed_id,uniqueness: {scope: :user_id}
  validates_associated :user
  validates_associated :followed_user

  private
  
  def not_follow_oneself
    if user_id == followed_id
      errors.add :followed_id,"Can't follow oneself"
    end
  end
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  attr_accessible :content,:timage
  belongs_to :user
  mount_uploader :timage, ImageUploader
  default_scope order("created_at DESC").includes(:favorites,:user)
  has_many :favorites,dependent: :destroy
  
  def favorited? user
    favorites.any? do |f|
      f.user.id == user.id
    end
  end  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :login, :image, :name, :screen_name, :bio
  attr_accessor :login
  # attr_accessible :title, :body

  has_many :tweets,dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follows
  has_many :following_users, through: :follows,source: :user
  has_many :inverse_follows,class_name: Follow,foreign_key: :followed_id
  has_many :followed_users, through: :inverse_follows

  mount_uploader :image, ImageUploader


  scope :except_user, ->(user_id) {
    where("id IS NOT ?", user_id)
  }


  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(["lower(username) = :value OR lower(email) = :value",{:value => login.downcase}]).first
  end

  def followed? user
    Follow.exists?(user_id: user.id,followed_id: self.id)
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @tweet = Tweet.find(params[:tweet_id])
    current_user.favorites.create(tweet: @tweet)
    redirect_to tweets_path
  end

  def destroy
    @tweet = Tweet.find(params[:tweet_id])
    @favorite = current_user.favorites.find_by_tweet_id(params[:tweet_id])
    @favorite.destroy
    redirect_to tweets_path
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    current_user.follows.create(followed_user: @user)
    redirect_to users_path
  end

  def destroy
    @user = User.find(params[:user_id])
    @follow = current_user.follows.find_by_followed_id(@user.id)
    @follow.destroy
    redirect_to users_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  skip_before_filter :authenticate_user!
  def index
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
    @tweet = Tweet.new
    @user = current_user
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tweets }
    end
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/new
  # GET /tweets/new.json
  def new
    @tweet = Tweet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tweet }
    end
  end

  # GET /tweets/1/edit
  def edit
    @tweet = Tweet.find(params[:id])
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = current_user.tweets.build(params[:tweet])
    @tweet.save
    redirect_to tweets_path
    # respond_to do |format|
    #  if @tweet.save
    #    format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
    #    format.json { render json: @tweet, status: :created, location: @tweet }
    #    redirect_to tweets_path()
    # else
    #    format.html { render action: "new" }
    #    format.json { render json: @tweet.errors, status: :unprocessable_entity }
    #  end
    #end
  end

  # PUT /tweets/1
  # PUT /tweets/1.json
  def update
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      if @tweet.update_attributes(params[:tweet])
        format.html { redirect_to tweets_path, notice: 'Tweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
   @users = User.except_user(current_user.id).all
  end

  def new
  end

  def create
  end

  def show
    @user = User.find(params[:name])
    @users = User.all
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/create.html.haml
%h1 Favorites#create
%p Find me in app/views/favorites/create.html.haml

app/views/favorites/destroy.html.haml
%h1 Favorites#destroy
%p Find me in app/views/favorites/destroy.html.haml

app/views/homes/index.html.haml
%h1 yakicame
%p つぶやきカメラなのでやきカメです
= link_to 'sign in',user_session_path()
= link_to 'sign up', new_user_registration_path()

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yakicame1</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<hr>
<% if user_signed_in? %>
  <%= link_to 'sign out',destroy_user_session_path,method: :delete %>
<% end %>

</body>
</html>

app/views/tweets/_form.html.haml
= form_for @tweet do |f|
  - if @tweet.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tweet.errors.count, "error")} prohibited this tweet from being saved:"
      %ul
        - @tweet.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :content
    = f.text_field :content

  .field
    = f.label :image
    = f.file_field :timage
  .actions
    = f.submit 'Save'

app/views/tweets/_tweet.html.haml
- @tweets.each do |tweet|
  = image_tag tweet.user.image_url(:thumb).to_s if tweet.user.image?
  %br
  = '@' + tweet.user.name
  %br
  = tweet.content if tweet.content?
  %br
  = image_tag tweet.timage_url(:thumb).to_s if tweet.timage?
  %br
  = link_to 'edit',edit_tweet_path(tweet) 
  = link_to 'delete',tweet_path(tweet),method: :delete,confirm: 'Are you ok?'
  - if tweet.favorited? current_user
    = link_to "unfavorite(#{tweet.favorites.size})",tweet_favorite_path(tweet),method: :delete
  - else
    = link_to "favorite(#{tweet.favorites.size})",tweet_favorite_path(tweet),method: :post
  %br  
  - tweet.favorites.each do |favorite|
    = User.find_by_id(favorite.user_id).screen_name
    = image_tag User.find_by_id(favorite.user_id).image_url(:thumb).to_s if User.find_by_id(favorite.user_id).image?
  %br  
%hr  

app/views/tweets/edit.html.haml
%h1 Editing tweet

= render 'form'

\|
= link_to 'Back', tweets_path

app/views/tweets/index.html.haml
#notice= notice
%h1 Listing tweets
= image_tag @user.image_url(:thumb) if @user.image?
= '@' + @user.name if @user.name?
= link_to 'profile',users_show_path(@user)
= link_to 'edit',edit_user_registration_path()




%table
  %tr
    %th tweet
    %th favorite
    %th follow
    %th follower
    
    %tr
      %td= @user.tweets.count
      %td= @user.favorites.count 
      %td= @user.follows.count
      %td= @user.inverse_follows.count

      
%br

= render 'form'
%hr
= render 'tweet'

app/views/tweets/new.html.haml
%h1 New tweet

= render 'form'

= link_to 'Back', tweets_path

app/views/tweets/show.html.haml
%p#notice= notice

%p
  %b User:
  = @tweet.user_id
%p
  %b Content:
  = @tweet.content

= link_to 'Edit', edit_tweet_path(@tweet)
\|
= link_to 'Back', tweets_path

app/views/users/index.html.haml
%h1 ユーザー一覧
%p フォローしましょう！

- @users.each do |u|
  %p
    = image_tag u.image_url(:thumb) if u.image?
    = u.name
    = u.bio
    = link_to 'detail',users_show_path(u)
    = link_to 'follow',user_follow_path(u),method: :post
    = link_to 'unfollow',user_follow_path(u),method: :delete
  %br

%hr
= link_to 'back to index',tweets_path

app/views/users/show.html.haml
%h1 Users#show
%p Find me in app/views/users/show.html.haml

- if @user.image? 
  = image_tag @user.image_url(:thumb)
= @user.name
= @user.screen_name
= @user.bio

= link_to 'all members',users_path
\|
= link_to 'back to index',tweets_path()
%hr

   